-- Run in Supabase SQL Editor. Use only the anon/public key in the app.
create table if not exists public.prediction_history (
  id bigint generated by default as identity primary key,
  event_id text unique not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  student_label text,
  predicted_grade double precision not null check (predicted_grade >= 0 and predicted_grade <= 100),
  risk_level text not null,
  inputs_json jsonb not null default '{}'::jsonb,
  model_method text,
  notes text
);

create table if not exists public.ai_chat_history (
  id bigint generated by default as identity primary key,
  event_id text unique not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  student_label text,
  prompt text,
  response text,
  context_json jsonb not null default '{}'::jsonb
);

create index if not exists prediction_history_user_created_idx
  on public.prediction_history(user_id, created_at desc);
create index if not exists ai_chat_history_user_created_idx
  on public.ai_chat_history(user_id, created_at desc);

alter table public.prediction_history enable row level security;
alter table public.ai_chat_history enable row level security;

drop policy if exists "Users manage own prediction history" on public.prediction_history;
create policy "Users manage own prediction history"
on public.prediction_history for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own AI chat history" on public.ai_chat_history;
create policy "Users manage own AI chat history"
on public.ai_chat_history for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
